### ISSUE TITLE
[4pt] Catalog of My Things: Kanban Board

### ISSUE THREAD

**Issue by peterdtitan** [peterdtitan/catalog-of-my-things#9]
## PROJECT BOARD
Below is a link to the Kanban Board for this project: 

**[Kanban Board via Projects](https://github.com/users/peterdtitan/projects/5)**

The project comprises 3 team members:

1. @peterdtitan (team member 1)
2. @preciousbetine (as member 2)
3. @Yidnekachew-cmd (as member 3)

Following this, the project requirements and tasks have been broken down evenly amongst the collaborators in this order.

**Comment by mukhammadrizooff** [comment]
Hi @peterdtitan, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

<img src="https://media4.giphy.com/media/Jq824R93JsLwZCaiSL/giphy.gif"/>

## Highlights
- Group work ✔️ 
- Good implementations ✔️ 

## Required Changes ♻️
- [ ] [REQUIRED] Good job so far! All cards should have the number of points in the `[Xpt]` prefix and assigne to `team members` like your other cards, please implement it provided below the `card` 🙏🏼 

![image](https://github.com/peterdtitan/catalog-of-my-things/assets/63915024/a0362bc0-9c1f-4194-afd7-d4149ba19c8c)

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
